---
title: "Cuarta clase 14-oct-2020: Algoritmos, iteraciones y condicionales."
output:
  html_document:
    df_print: paged
---



```{r message=FALSE, warning=FALSE, eval=F}
install.packages('stringi', dependencies = T, quiet = T)
#install.packages('svMisc', dependencies = T, quiet = F)
```

```{r message=FALSE, warning=FALSE, eval=F}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager", dependencies = T, quiet = T )

BiocManager::install("GEOquery", checkBuilt = T, ask = F )
```


```{r message=FALSE, warning=FALSE}
largo <- 60
sample(letters, largo, replace = T) -> a
sample(1:10, largo, replace = T)    -> b

library(stringi)
stri_rand_strings(largo,8, pattern = "[A-B0-9t-z]") -> my.rows
stri_rand_strings(2,4, pattern = "[A-G]") -> my.cols

library(magrittr)
cbind(a,b) %>% set_rownames(my.rows) %>% set_colnames(my.cols) -> my.mat
my.mat[,colnames(my.mat)[1]]
my.mat[2,]
my.mat[,2] %<>% as.numeric() 
```
### While loop
```{r}
i=0
while(i<nrow(my.mat)){
                      i = i +1
                      paste('looping at ',i) %>% print
                      }
```
```{r}
i=0
while(i<nrow(my.mat)){
                      i = i +1
                      paste('looping at ',i) %>% print
                      }
```
### For loop
```{r}
for (i in 0:10){
  print(i)
  Sys.sleep(0.2)
}
```
### For loop with progress bar
```{r message=FALSE, warning=FALSE}
pb <- txtProgressBar(0,nrow(my.mat), style = 3)
for(i in 1:nrow(my.mat)) {
   setTxtProgressBar(pb, i)
   Sys.sleep(.1)
    if (i == nrow(my.mat)) print('OK!')
 }
```

### Progress bar with While loop
```{r}
i=0
pb <- txtProgressBar(0,nrow(my.mat), style = 3)
while(i<nrow(my.mat)){
                      i = i +1
                      setTxtProgressBar(pb, i)
                      Sys.sleep(.1)
                      #paste('looping at ',i) %>% print
                      }
```

### Repeat loop
```{r}
i=0
repeat{
       i = i +1
       setTxtProgressBar(pb, i)
       Sys.sleep(.1)
  
       if( !i<nrow(my.mat) ) {break}
}
```
### BREAK

```{r}

threshold <- 5

for (i in 1:nrow(my.mat)) 
    {  Sys.sleep(.2)
  print(paste("lopping at  ", i)) 
    if (my.mat[i,][2] %>% as.numeric() > threshold)  
    { 
        print(paste("We superpass ", threshold)) 
        break
    } 
   
} 
```

```{r}
i=0
pb <- txtProgressBar(0,nrow(my.mat), style = 3)
while(i<nrow(my.mat)){
                      i = i +1
                      paste('looping at ',i) %>% print
                      setTxtProgressBar(pb, i)
                      Sys.sleep(1)
                          if(i==5)
                            break 
                      }

```

## NEXT
```{r message=FALSE, warning=FALSE}


mis_numbs = NA
mis_letrs = NA
i  = 0
p1 = 0
p2 = 0
for(i in 1:length(c(my.mat))){
                         my.item <- c(my.mat)[i]
                         if(!is.na( as.numeric(my.item))) {p1 = p1 +1
                                                          mis_numbs[p1] <- as.numeric(my.item)
                                                          next}
                         p2 = p2 + 1 
                         mis_letrs[p2] =  my.item
}
mis_letrs
mis_numbs
```

```{r message=FALSE, warning=FALSE}
mis_numbs = NULL
mis_letrs = NULL
i  = 0
for(i in 1:length(c(my.mat))){
                         my.item <- c(my.mat)[i]
                         if(!is.na( as.numeric(my.item))) {
                                                          mis_numbs %<>% c(as.numeric(my.item))
                                                          next}
                        
                         mis_letrs %<>% c(my.item) 
}
mis_letrs
mis_numbs
```


```{r message=FALSE, warning=FALSE}
mis_numbs = NULL
mis_letrs = NULL
i  = 0
repeat{i=i+1
       if(i>length(c(my.mat))){break}

       my.item <- c(my.mat)[i]
       if(!is.na( as.numeric(my.item))) {
                                        mis_numbs %<>% c(as.numeric(my.item))
                                        next}
      mis_letrs %<>% c(my.item) 
}
mis_letrs
mis_numbs
```
```{r message=FALSE, warning=FALSE}
mis_numbs = NULL
mis_letrs = NULL
i  = 0
repeat{i=i+1
       if(i>length(c(my.mat))){break}
       my.item <- c(my.mat)[i]
       if(!is.na( as.numeric(my.item))) {mis_numbs %<>% c(as.numeric(my.item))}
       else{mis_letrs %<>% c(my.item)}
        
}
mis_letrs
mis_numbs
```
### Ejemplo: Extraer títulos desde lista con metadata de RNAseq
```{r message=FALSE, warning=FALSE}
library(GEOquery)
library(tidyverse)

codes <- c('GSE159378', 'nada' , 'GSE159377',  'GSE154900', 'GSE151154', 'nada', 'GSE146754' )

metadata.list <- list()

for(i in 1:length(codes)){
  down.path                  <- NULL
  try(
  getGEOfile(codes[i])       -> down.path) 
  if (down.path %>% is.null){next}
  getGEO(filename=down.path) -> soft
  soft                       -> metadata.list[[i]]
}

#metadata.list %>% glimpse
#metadata.list %>% length

Titles <- NULL
for(i in 1:length(metadata.list)){
                                   metadata.list[[i]]               -> extracted.metadata
                                   if (extracted.metadata %>% is.null){next}  
  
                                   extracted.metadata %>% slotNames -> my.slots

             for(j in 1:length(my.slots)){
                                          slot(extracted.metadata,my.slots[j] ) %>% names -> my.names

             if(str_detect(my.names, '(t|T)itle') %>% any){
                                              my.names[str_detect(my.names, '(t|T)itle')]       -> my.title0
                                              slot(extracted.metadata,my.slots[1])[[my.title0]] -> my.title
                                              Titles %<>% c(my.title)
                                              }}}

Titles

```

