--- 
title: "Principios de bioinformática y ciencias de biodatos"
author: "Alejandro Acevedo-Aracena, _PhD_^[_FONDECYT Postdoctoral Fellow_, Universidad de Chile, deepen.data@gmail.com]; Manuel Muñoz-González^[_Pregrado_, Universidad de Chile]"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Clases de bioinformática para gente no informática."
---

# Presentación { .unnumbered}

Los avances en la obtención de datos biológicos asociados a genes, proteínas y 
metabolitos han dado lugar a un rápido aumento del volumen y complejidad de 
datos publicados en distintos repositorios de libre acceso 
(por ejemplo _Gene Expression Omnibus_ de NCBI).
Actualmente se requiere de bioinformáticos que apliquen herramientas 
bioinformáticas y ciencia de datos para generar resultados biológicamente 
interpretables desde datos complejos y diversos.

Este curso está orientado a **alumnos sin ningún conocimiento
previo sobre programación y computacional ni bioinformática**. Se
espera que al final del curso los alumnos dominen herramientas
básicas de bioinformática y principios generales de ciencia de datos
para aplicarlos en sus respectivas áreas de investigación.
