---
title: "Tercera clase: modificación de columnas con 'mutate', operadores de tipo 'pipes', detección/extracción de patrones con expresiones regulares y guardar en formato R."
author: "Acevedo, A. & Munoz, Manuel. U. de Chile. "
date: "08 octubre 2020."
output:
  html_document:
    df_print: paged
---

<!-- TODO: insertar video despues de la clase -->

```{r Librerias a utilizar}
library("tidyverse") # Muchas cosas cool

library("dplyr")     # Manipulación de datos mediante gramatica propia
library("magrittr")  # Operadores cañeria (pipes) %>%)
library("readr")     # Traducción (pharsing) de archivos a una tibble
library("stringr")   # Stringr
```

La función _mutate()_ de **dplyr** permite crear nuevas variables manteniendo las ya existentes. 
Por ejemplo, sacando el promedio de dos variables u operaciones similares. 

```{r echo=TRUE, message=FALSE, warning=FALSE, paged.print=TRUE}
# Importando datos de un CSV
data.location <- 'https://raw.githubusercontent.com/DeepenData/clases/master/06_mutate_pipes_regex/data_oct_08_2020.csv' # Reemplazar por dirección local si bajan el archivo
sim.without.outliers <- read_csv(data.location) # Importa la data a "sim.without.outliers"

# Modificando la tabla con mutate() para calcular el Fold-change (log2/log2)
sim.without.outliers %>% # Tirando data por la cañeria 
  # Hace un promedio de las columnas TREAT(MENT)
  mutate(`Mean treatment` = rowMeans(select(., starts_with("treat")))) %>%
  # Hace un promedio de las columnas CONTROL 
  mutate(`Mean control` = rowMeans(select(., starts_with("control")))) %>%
  # Calcula el fold-change de TRATAMIENTO sobre CONTROL
  mutate(`log2Ratio` = log2(.[['Mean treatment']] / .[['Mean control']])) %>% 
  # Renombra las columas para ponerles un identificador
  rename_at(vars(matches('^treat|^contr|^mean|log2', ignore.case = TRUE)), 
            # TODO: rename_at() esta obsoleta y ahora deberia ser rename_with()
            funs(paste0(., ' A'))) # Identificador " A" al final de cada columna
            # TODO: sugiero eliminar " A" de aqui y dejarlo solo en la función más abajo

# Creamos funciones personalizadas
# Aumenta por el cambio +- fracción del cambio. Es decir 3 +- 0.3 (2.7-3.3)
an.increase             <- function(x,change=3,fraction=.1) 
{runif(1, 
       min= (change*x - fraction*(change*x)),
       max= (change*x + fraction*(change*x)))}

# Disminuye por el cambio +- fracción del cambio. Es decir 0.2 +- 0.1 (0.1-0.3)
a.decrase               <- function(x,change=.2,fraction=.1) 
{runif(1,
       min= (change*x - fraction*(change*x )),
       max=(change*x + fraction*(change*x )))}

# TODO: sugiero meter esto más arriba de las an.increase y a.decrease, junto al ejemplo
# Repite la creación de fold-change que hicimos y lo hace función
generate_mean_log2Ratio <- function(x, a.letter) 
  {x %>% # Toma la entrada "x
    mutate(`Mean treatment` = rowMeans(select(., starts_with("treat")))) %>%  # Promedio Tratamiento
    mutate(`Mean control` = rowMeans(select(., starts_with("control")))) %>%  # Promedio Control
    mutate(log2Ratio = log2(.[['Mean treatment']] / .[['Mean control']])) %>% # Fold-change
    rename_at(vars(matches('^treat|^contr|^mean|log2', ignore.case = TRUE)),  # No hace nada?
              funs(paste0(., a.letter)))}


# Mutate(across(...)) modifica multiples columnas con la función que le demos

# TODO: esto repite lo de arriba, pero creo que queda más claro con los A,B,C de una
sim.without.outliers %>% 
  generate_mean_log2Ratio(' A') -> A # Calcula el fold-change inicial

sim.without.outliers %>% 
  mutate(across(starts_with("treatment"), an.increase)) %>% 
  generate_mean_log2Ratio(' B') -> B # Fold-change aumenta 1.4-1.7 veces

sim.without.outliers %>% 
  mutate(across(starts_with("treatment"), a.decrase)) %>% 
  generate_mean_log2Ratio(' C') -> C # Fold-change disminuye -3.3 - -1.7 veces


# Creando el dataset final
cbind(A, # Parte con la data A
      select(B, matches('tre|con|log')), # Añade columnas de B
      select(C, matches('tre|con|log'))) -> final.data # Añade columnas de C y guarda
final.data
```


```{r echo=TRUE, fig.height=3, fig.width=3, message=FALSE, warning=FALSE, paged.print=TRUE}
final.data %$% cor(`log2Ratio A`,`log2Ratio B`) # Correlación entre A y B
final.data %$% cbind(`log2Ratio A`, `log2Ratio B`, `log2Ratio C`) %>% colSums -> my.col.sum
my.col.sum %>%  subset(.>0) -> my.col.sum
my.col.sum %<>% subset(.>0)
final.data %>% select(matches('log2')) %T>% plot() %>% select(matches('B|C')) -> my.cols
```


```{r}

my.terms <- c('system 1','system 2.7.9','subsystem A','subsystem B and A')
sample(my.terms, nrow(final.data)/2,  replace = T)        -> terms.col
sample(final.data$name, nrow(final.data)/2,  replace = F) -> names.sample
data.frame(terms.col,names.sample) -> my.info
inner_join(final.data,my.info, by = c('name'='names.sample'))-> final.data.with.terms
full_join(final.data,my.info, by = c('name'='names.sample')) -> final.data.with.terms.nas
```

```{r}

final.data.with.terms.nas %>% filter(`log2Ratio A` < 0 & `log2Ratio B` < 0 & `log2Ratio C` < 0) %>% drop_na 
```
```{r}


final.data.with.terms.nas %>% .[['name']] %>% str_detect('DE') %>% which

final.data.with.terms.nas %>% .[['name']] %>% str_extract('[aA-zZ]E.1\\d$') %>%  .[!is.na(.)]
final.data.with.terms.nas %>% .[['name']] %>% str_extract('[aA-zZ]E.1\\d+') %>% .[!is.na(.)] 
final.data.with.terms.nas %>% .[['name']] %>% str_extract('[aA-zZ]E.1\\d.+') %>% .[!is.na(.)]
final.data.with.terms.nas %>% .[['terms.col']] %>% str_extract('^s.*m') %>% na.exclude() %>% sample(10)
final.data.with.terms.nas %>% .[['terms.col']] %>% str_replace('subsystem','comparment') %>% na.exclude() %>% sample(10)
```

```{r}
final.data.with.terms.nas %>% filter(str_detect(name, regex('de.*', ignore_case = T)) & str_detect(terms.col, regex('B.*A', ignore_case = F)))
```

```{r}
final.data.with.terms.nas %>% filter(str_detect(name, regex('de.*', ignore_case = T)) & str_detect(terms.col, regex('\\d.\\d', ignore_case = F)) & `log2Ratio C` <0) %>% select(matches('log|name|term')) 
```

```{r}


'system 2.7.9' %in% final.data.with.terms.nas$terms.col
final.data.with.terms.nas %>% {if('system 2.7.9 ff' %in% final.data.with.terms.nas$terms.col) print('ok') else str_extract(.[['terms.col']], 'system.*' )} %>% na.omit %>% unique -> unicos


```

```{r}
list.files(path = ".", pattern = 'aa',  ignore.case = T)
list.files(pattern = 'csv', full.names = T)

# Save an object to a file
saveRDS(final.data.with.terms.nas, file = "final.data.with.terms.nas.rds")
# Restore the object
hola <- readRDS(file = "final.data.with.terms.nas.rds")
# Save multiple objects
save(final.data.with.terms.nas, unicos, file = "some_data.RData")
load("some_data.RData")
```
