---
title: "R Notebook"
output: html_notebook
---


```{r}
library(methods)
library(tidyverse)

setClass("genes", 
  slots = c(
    indentifiers    = "data.frame",
    gene_to_reactions   = "data.frame"))

setClass("reactions", 
  slots = c(
    indentifiers  = "data.frame", 
    stoichiometry = "data.frame", 
    subsystem     = "data.frame"))

setClass("metabolites", 
  slots = c(
    indentifiers = "data.frame", 
    compartemt   = "data.frame",
    formula      = "data.frame"))


setClass("metabolism", 
  slots = c(
    genes = 'genes', 
    reactions = 'reactions',
    metabolites = 'metabolites'))


```
```{r}
library(magrittr)
genes_url       <- 'https://raw.githubusercontent.com/DeepenData/clases/fb3e5b3f7c9aca0c13d7eebe217cde9fe6b087bf/04-filters-programacion-funcional-apply-map/recon3_genes_to_reactionIDs.csv'
metabolites_url <- 'https://raw.githubusercontent.com/DeepenData/clases/fb3e5b3f7c9aca0c13d7eebe217cde9fe6b087bf/04-filters-programacion-funcional-apply-map/recon3_metabolite_metadata.csv'
reactions_url   <- 'https://raw.githubusercontent.com/DeepenData/clases/fb3e5b3f7c9aca0c13d7eebe217cde9fe6b087bf/04-filters-programacion-funcional-apply-map/recon3_reactions_metadata.csv'


import_my_csv <- function(url){readr::read_csv(url) %>% dplyr::select(-matches("x1"))}

```

```{r message=FALSE, warning=FALSE}
genes_df          <- import_my_csv(genes_url) 
human_genes       <- new("genes", indentifiers = genes_df["Gene_ID"], gene_to_reactions = genes_df["Reactions"]) %>% glimpse

reactions_df      <- import_my_csv(reactions_url) 
human_reactions   <- new("reactions", indentifiers =  reactions_df[c('rxn_ids','rxn_names')], stoichiometry = reactions_df['reactions'], subsystem = reactions_df["rxn_subsystems"]) %>% glimpse

metabolites_df    <- import_my_csv(metabolites_url) 
human_metabolites <- new("metabolites", indentifiers =metabolites_df['ID', 'Name'], compartemt = metabolites_df['Compartment'], formula = metabolites_df['Formula'])    %>% glimpse


create_metabolism <- function(genes =  genes, reactions = reactions, metabolites = metabolites) {
  new("metabolism", genes =  genes, reactions = reactions, metabolites = metabolites) %>% glimpse}


human_metabolism_0  <- create_metabolism( genes =  human_genes, reactions = human_reactions, metabolites = human_metabolites)
```
```{r}
create_metabolism <- function(genes =  genes_df, reactions = reactions_df, metabolites = metabolites_df) {

genes       <- new("genes", indentifiers = genes_df["Gene_ID"], gene_to_reactions = genes_df["Reactions"])
reactions   <- new("reactions", indentifiers =  reactions_df[c('rxn_ids','rxn_names')], stoichiometry = reactions_df['reactions'], subsystem = reactions_df["rxn_subsystems"])
metabolites <- new("metabolites", indentifiers =metabolites_df['ID', 'Name'], compartemt = metabolites_df['Compartment'], formula = metabolites_df['Formula'])  

new("metabolism", genes =  genes, reactions = reactions, metabolites = metabolites) %>% glimpse}
```


```{r}
human_metabolism <- create_metabolism(genes =  import_my_csv(genes_url) , reactions = import_my_csv(reactions_url), metabolites = import_my_csv(metabolites_url))
```

Accessors:  setters and getters
```{r}
setGeneric("genes",   function(x) standardGeneric("genes"))
setMethod("genes", "metabolism", function(x) slot(x@genes, 'indentifiers')[[1]])

genes(human_metabolism)

setGeneric("genes<-", function(x, value) standardGeneric("genes<-"))
setMethod("genes<-", "metabolism", function(x, value) {
  x@age <- value
  x
})

```

```{r}
setGeneric("rxns_by_genes",   function(x) standardGeneric("rxns_by_genes"))
setMethod("rxns_by_genes", "metabolism", function(x){ 
  slot(x@genes, 'gene_to_reactions') -> gene_to_reactions
  slot(x@genes, 'indentifiers')  -> genes
  tibble(genes, gene_to_reactions )
  })
```


```{r}
rxns_by_genes(human_metabolism)
```


```{r}
setMethod("age<-", "Person", function(x, value) {
  x@age <- value
  x
})
```








